name: SimpleHungerGames
version: "1.0"
main: com.loriswit.shg.Shg
api-version: "1.18"

commands:
  start:
    description: Starts the game
    usage: /start
  end:
    description: Ends the game
    usage: /end
