name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: jetbrains

    - name: Build with Maven
      run: mvn install

    - uses: actions/upload-artifact@v4
      with:
        name: shg.jar
        path: target/shg-1.0-SNAPSHOT.jar
